[project]
name = "run-scraper"
version = "0.1.0"
description = "Scraper"
authors = [
    {name = "Jocelyn Thai, jocelynvthai@berkeley.edu"}
]
package-mode = false


[tool.poetry.dependencies]
python = ">=3.10"
requests = "^2.32.4"
google-cloud-bigquery = "^3.35.1"
slack-sdk = "^3.36.0"
selenium = "^4.34.2"
python-dotenv = "^1.1.1"
selenium-stealth = "^1.0.6"


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
